"""new fields in user model

Revision ID: 895075b6c6ca
Revises: cb78077b0a2a
Create Date: 2021-09-04 21:46:58.710752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895075b6c6ca'
down_revision = 'cb78077b0a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
